global:
  domain: argocd.test

controller:
  replicas: 1

configs:
  params:
    server.insecure: true

server:
  replicas: 1
  ingress:
    enabled: true
    ingressClassName: nginx

repoServer:
  replicas: 1

applicationSet:
  replicas: 0

notifications:
  enabled: false
